language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
<<<<<<< HEAD
- npm test
- npm run build
deploy:
  provider: releases
  api_key:
    secure: CJ249p1kaJpMSu3p/izQpYr+IUtXxVKxUr5cI8dhSnY+ZX1X4d+dJqLmRzmuWOLnfJLkx9SBKfyt5hMI2cAxehWqqXNlQsmlcrBRDORG0CC2MVkIe52cgZPyRM6RlU7MSAc2BFIhyMfvC5O+oMSsq4Llaz+xFsYQcIshnJHE4Axh2xbSlvDsNV/KrsQLS9w+PBw+Oo3CJ3Vv57SoR5d78q7PmjduH18mUJ+n8MYlDXIpLeUHMWS9iyzIxdQSNmCvmfWA+lC75N5kJR6rlIq/aAVTUA2bN4swm0r0wc3Z/LpYa9GLacGZnk3+X+AWllLT6vLTyq7c/iqeZRuzOcTE8/d/7qdoYBxgI8QTr29UCVR9WldsoAzsBqxt6IxtY/f+y1xSjYTHWLPTnQj0YKMVPamquTQyKIqgt0D/l+LBMtTThg1NeP6HvWIUae9uilcaWV51s621V/ZlXx6GC+oBI2SJY/1OW0pKyW16Lsle83DKhhf9xb2/x5D+qgWxXnIK6Xd5EyoU/1DtO06gAjLrHTIAIbc8fmwf6HWN/+s2QKNMDQNXoGPlk9QHPKdq6omFQSdv8Pm43pAJ9SdHqA/Xs3gaowhcGDzpkWe3pYNl7kHuy/2oV9+S54cafSEHkmYWAYqQBt6xJYiFIwuKBGlwCd745R6RxZbaZYZHwQ/l9yg=
  file: ''
=======
  - npm test
  - npm run build
env:
  global:
   - secure: "Avco04igRW1/gGB5AcZRPBk4upge2GPwdz8QHc++vmQmF8oviEGj1kNzFXfqjgcIHVKRJ7JP82ixdPpQdAX26MHl1CTsHUHD08LjWJRQoaN2HRxVreoRLi33LYewNfXza3qzS9t6EK0rjFg9x0i1TfecQn4hNY6yc/l8CYD8hWtxJvzaO31URwlFpG/5O8KPoObVCpaH7ZYeSKogqKrnO5mpKhp5YU1HAZUTUARV7AwbDJlmk7t6Y9NHj3qY5UGtZbabKuWXEXj3phqZxEhTOREHTOJXWAW6VLSoZ5r/HplEI8ZB70K/sPzgtVe3E2ddPF3E6H/sK6ty6JavG1CWQc+1stM2UeFuS7ZKb21pe8SGd3Uqh5hWz7D8OtRUnhyST3i4w4mg60Rw+yF8aClluaZ6biLd1Jv6k+J19/A9jK4m75pYSgKpkqzDdslxBd+xUYIC7xagaimmuMQEGiCYCFubqlz94P4HfLZqgysMI3M3da/5rAIx2WE9QzIR/5J28+zVEAuDvXkCQsnMKLCeVvH/qw/eV4NzBABI8LpZrCZLTRhXldfxRSjOUTGg+Obsxu8czUgxea+KG0Up7PchzqLu7EiRoOVM9zAa5R9oCybeo0Yj7lM0drR+YitMsK42PvLXxP3lZUd9B9D8ZCtQzNZRVB6N/ogzbF5szWd9OL8="


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
>>>>>>> 9a3a286ba4eeb708e5e4a334a7d0a0617c596302
  on:
    repo: madhur4444/PersonalWebsite
env:
  global:
  - secure: KaMZz23Dx9fnA7gJ0llapmbORxuZXBm8sGuWNq4rIP+K0+lpFS9EV0oIdUJ+cFoUAa4R42VV84vNEcobCLIIcbT9bDbU+C2p14k7v3/MFXsxXqdyk9FYiJDfmAW21gFuVUloKrOXpBukavTfSC6lh6QTSC4y/IuVScMq1Te/2SH9W3Ts1At0AxUY5JwNhf1lGzHGRPUqRZNcrOPNUYkjMOASQK0Jlgc3yi05reyzPwvwzpz9ZLa6SQsMxJKAcA9oeBw8LBWQxY5I0bKnrJJk7NyGMJjotERjjXknNOsaHEdwDfQxZxS8vV19HkOByFgkvkNil5ZqU2wkFWF9a+OI7Th+1tddGqvDAeeahntc1reNZLi2tDcT2iGHst+6GXmubfE1LgdenWlZbK9lznU9Un2dGl40yj8/9NxoLXLndUO6YH5KYmWwdPtjZ7GvIl552M79Csmh6s0yrCBx3zuNmo0GA3s2iZJmd/jMADXAUnSb/sGPPurXUtaqm34PIxyjTx8mW/8aJVBEuWd1S0DD6OApeODuF+SjR8pKM1URqy8Q41Bo/uqEn+419El3rpFG9wemrIcByQZkYyZtuVfwVXMNKhmnnxCHQ0Q7wJkxK0gKcKFwYLb89U8Chv0JBvPXtzLZtzjbyBTdSv3mTcWXHdlFqwLHAgGBTIUnJMMq6rs=
  - secure: NbaeUUbNz3le3HEyPgaoQO18O0HRQregStKHmsynJ5dKiVK2lp5YeZwjdU9sYCMFCoGDOLrWgZDKhwnI7nHITtpHPSzL8WPqACG0xoKOfn10Br2hqyLwlU3HrNjpGtkpsWVMfwnEfToD8CIQ1wnKKyeu2S2Y6gZ3a/jTH2fGKpI+PQPgF8LIPYcJjmPM6lllR3mwYD3fHG4EMVEXe42xB4luN4NCMZRXAYHbATOWHwJL9Pu/Ma0ZA8Sq8YIa+fvfpa4MI+u6xEMYN6avpxsfFxeM3kbyWSdEnfRbIuFK0OBt4u5NSP3fE3NyWvvzrLb8nMY/XymMf9EX9J39zgQY8t7WxyGcnKxK2d6FqsBe4CLTjHPfLH30ZsqpHZ2J4RXj8tDEsHEPSeZcGwJ83Ij69tkaTmGh2imlRHWNBx6rWZEvIGLMnYFc4IM3nfKMScAd/PVtcI1r/Rl64z1n9wo9aAaypnvyPYgpgtJedcgmYzbn9x5uXGiO79vWjSCMj+7H+3lnFLozsatsQOyA/FGIUVoWNJUCP3OAun19JydHbKcwwULR8HKgTWQaf8fCCHNgPbkIux0A1ZEFs3m733nJ9AbYvR4yFIPhBARl0l68s6k1zFNQcv+9jwlwRIAtXwMCsDXJmRrgP/A26o8VbHm3DJrZnX3upL1JqBtVnBpdspU=
